quarkus.http.port=8080

quarkus.http.cors.enabled=true
quarkus.http.cors.origins=http://localhost:3000
quarkus.http.cors.methods=GET,POST,OPTIONS
quarkus.http.cors.headers=accept,content-type

quarkus.rest-client.frankfurter-api.url=https://api.frankfurter.dev
